# Generated by Django 6.0.8 on 2026-08-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("sector", models.CharField(blank=True, max_length=128)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this instrument should be included in data backfills and strategies.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exchange", "symbol"), name="unique_symbol_per_exchange"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(choices=[("1d", "Daily")], default="1d", max_length=8),
                ),
                ("timestamp", models.DateTimeField(help_text="Bar date/time, in UTC.")),
                ("open", models.DecimalField(decimal_places=4, max_digits=14)),
                ("high", models.DecimalField(decimal_places=4, max_digits=14)),
                ("low", models.DecimalField(decimal_places=4, max_digits=14)),
                ("close", models.DecimalField(decimal_places=4, max_digits=14)),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "is_anomaly",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged by the data provider as a likely data-quality issue.",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_bars",
                        to="marketdata.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "timeframe", "-timestamp"],
                        name="marketdata__instrum_2ca7c5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "timeframe", "timestamp"),
                        name="unique_bar_per_instrument_timeframe_timestamp",
                    )
                ],
            },
        ),
    ]
