# Generated by Django 6.0.8 on 2026-09-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketdata", "0001_initial"),
        ("modeling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("feature_spec", models.JSONField(blank=True, default=list)),
                ("target_spec", models.JSONField(blank=True, default=dict)),
                ("train_start", models.DateField(blank=True, null=True)),
                ("train_end", models.DateField(blank=True, null=True)),
                (
                    "holdout_fraction",
                    models.FloatField(
                        default=0.2,
                        help_text="Trailing fraction of rows scored for every candidate (0.05-0.5).",
                    ),
                ),
                (
                    "search_space",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'estimators': [...], 'param_grids': {key: {param: [values]}}}. An estimator with no grid entry is tried once at its defaults.",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("grid", "Grid (every combination)"), ("random", "Random sample")],
                        default="grid",
                        max_length=8,
                    ),
                ),
                (
                    "max_candidates",
                    models.PositiveIntegerField(
                        default=40, help_text="Cap on candidates evaluated in one run."
                    ),
                ),
                ("random_seed", models.IntegerField(default=0)),
                (
                    "scoring",
                    models.CharField(
                        blank=True,
                        help_text="Metric key to rank by. Blank = the task default.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The trading model this search was seeded from (provenance only).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_searches",
                        to="modeling.tradingmodel",
                    ),
                ),
                (
                    "instruments",
                    models.ManyToManyField(
                        blank=True, related_name="model_searches", to="marketdata.instrument"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "model searches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("estimator_key", models.CharField(max_length=64)),
                ("estimator_params", models.JSONField(blank=True, default=dict)),
                ("params_hash", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("failed", "Failed")], default="ok", max_length=8
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("fit_seconds", models.FloatField(blank=True, null=True)),
                ("predict_seconds", models.FloatField(blank=True, null=True)),
                (
                    "predict_latency_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Holdout predict wall time per row, milliseconds.",
                        null=True,
                    ),
                ),
                ("model_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_pareto",
                    models.BooleanField(
                        default=False,
                        help_text="Not dominated on (score, fit time, predict latency, size).",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_results",
                        to="modelsearch.modelsearch",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-score"],
            },
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="best_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="modelsearch.modelsearchresult",
            ),
        ),
        migrations.CreateModel(
            name="ModelSearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("candidates_total", models.PositiveIntegerField(blank=True, null=True)),
                ("candidates_ok", models.PositiveIntegerField(blank=True, null=True)),
                ("candidates_failed", models.PositiveIntegerField(blank=True, null=True)),
                ("dataset_rows", models.PositiveIntegerField(blank=True, null=True)),
                ("feature_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="modelsearch.modelsearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="modelsearchresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="modelsearch.modelsearchrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelsearchresult",
            constraint=models.UniqueConstraint(
                fields=("run", "params_hash"), name="unique_candidate_per_run"
            ),
        ),
    ]
