# Generated by Django 6.0.8 on 2026-09-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsearch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelsearch",
            name="scoring_mode",
            field=models.CharField(
                choices=[
                    ("holdout", "Trailing holdout"),
                    ("walk_forward", "Walk-forward (refit per fold)"),
                ],
                default="holdout",
                help_text="Holdout: one trailing split, fast. Walk-forward: refit every candidate on each backtesting.walkforward fold and pool the out-of-sample predictions - slower (candidates x folds fits) but the accuracy read the single holdout can diverge from.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="wf_gap",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Walk-forward only. Embargo sessions between a fold's train end and test start.",
            ),
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="wf_scheme",
            field=models.CharField(
                choices=[("expanding", "Expanding window"), ("rolling", "Rolling window")],
                default="expanding",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="wf_step",
            field=models.PositiveIntegerField(
                default=21,
                help_text="Walk-forward only. Sessions the window advances between folds.",
            ),
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="wf_test_span",
            field=models.PositiveIntegerField(
                default=21,
                help_text="Walk-forward only. Sessions scored per fold before the next refit.",
            ),
        ),
        migrations.AddField(
            model_name="modelsearch",
            name="wf_train_span",
            field=models.PositiveIntegerField(
                default=250, help_text="Walk-forward only. Sessions of training history per fold."
            ),
        ),
        migrations.AddField(
            model_name="modelsearchresult",
            name="wf_folds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Walk-forward mode only: folds pooled into this candidate's score/metrics.",
                null=True,
            ),
        ),
    ]
