# Generated by Django 6.0.8 on 2026-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsearch", "0002_modelsearch_scoring_mode_modelsearch_wf_gap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelsearch",
            name="auto_ensemble_top_k",
            field=models.PositiveIntegerField(
                default=3,
                help_text="After scoring the sweep, also try one voting_ensemble candidate averaging the top N distinct-estimator results (regression tasks only). 0 or 1 disables.",
            ),
        ),
    ]
