# Generated by Django 6.0.8 on 2026-08-08 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "key",
                    models.CharField(
                        help_text="Registered strategy key, e.g. 'ma_crossover'. See strategies.registry.",
                        max_length=64,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keyword args passed to the strategy class, e.g. {'fast_period': 10}.",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instruments",
                    models.ManyToManyField(
                        blank=True, related_name="strategies", to="marketdata.instrument"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "strategies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManualSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "action",
                    models.CharField(
                        choices=[("buy", "BUY"), ("sell", "SELL"), ("hold", "HOLD")], max_length=8
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_signals",
                        to="marketdata.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "date"), name="unique_manual_signal_per_day"
                    )
                ],
            },
        ),
    ]
