# Generated by Django 6.0.8 on 2026-08-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account this strategy trades on when active. Required for run_trading_cycle to submit orders for it - a Strategy without one is never executed live.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategies",
                to="portfolio.account",
            ),
        ),
    ]
