# Generated by Django 6.0.8 on 2026-09-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketdata", "0001_initial"),
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_directional_accuracy",
                    models.FloatField(
                        default=0.55,
                        help_text="Suppress the signal unless the model's trailing out-of-sample up/down hit-rate is at least this (0-1).",
                    ),
                ),
                (
                    "min_skill",
                    models.FloatField(
                        default=0.0,
                        help_text="Suppress the signal unless skill-vs-naive is at least this. 0 disables the check; >0 also requires skill to be computable.",
                    ),
                ),
                (
                    "min_expected_move_pct",
                    models.FloatField(
                        default=1.0,
                        help_text="A predicted move smaller than this (in %) is reported FLAT and not delivered - it is not worth trading.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_items",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "trading_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_items",
                        to="modeling.tradingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument__symbol"],
            },
        ),
        migrations.CreateModel(
            name="WeeklySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("as_of", models.DateField(help_text="The Monday the call was made for.")),
                ("target_date", models.DateField(help_text="The Friday the call is about.")),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("flat", "Flat")], max_length=8
                    ),
                ),
                (
                    "expected_return_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Signed predicted move into the target close, in %.",
                        null=True,
                    ),
                ),
                ("predicted_close", models.FloatField(blank=True, null=True)),
                (
                    "reference_close",
                    models.FloatField(
                        blank=True, help_text="Last close known when the call was made.", null=True
                    ),
                ),
                ("flat_threshold_pct", models.FloatField(default=1.0)),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Model's trailing directional accuracy at send time.",
                        null=True,
                    ),
                ),
                ("model_stats", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending delivery"),
                            ("sent", "Sent"),
                            ("suppressed", "Suppressed (failed gate)"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("suppression_reason", models.CharField(blank=True, max_length=255)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("actual_close", models.FloatField(blank=True, null=True)),
                ("actual_return_pct", models.FloatField(blank=True, null=True)),
                ("was_correct", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_signals",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "model_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="modeling.modelprediction",
                    ),
                ),
                (
                    "trading_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_signals",
                        to="modeling.tradingmodel",
                    ),
                ),
                (
                    "watch_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="signalfeed.watchitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "instrument__symbol"],
            },
        ),
        migrations.AddConstraint(
            model_name="watchitem",
            constraint=models.UniqueConstraint(
                fields=("instrument", "trading_model"), name="unique_watchitem_per_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklysignal",
            constraint=models.UniqueConstraint(
                fields=("instrument", "trading_model", "target_date"),
                name="unique_weekly_signal_per_model_target",
            ),
        ),
    ]
