# Generated by Django 6.0.8 on 2026-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchitem",
            name="kelly_fraction",
            field=models.FloatField(
                blank=True,
                default=0.5,
                help_text="Fraction of the model's directional edge to bet (0.5 = half-Kelly). 0 sizes flat at max_position_pct for every deliverable call.",
            ),
        ),
        migrations.AddField(
            model_name="watchitem",
            name="max_position_pct",
            field=models.FloatField(
                blank=True,
                default=10.0,
                help_text="Hard cap on one call's suggested size, as a %% of sizing_capital.",
            ),
        ),
        migrations.AddField(
            model_name="watchitem",
            name="sizing_capital",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Notional pool a single delivered call is sized against. 0 disables the position-sizing hint. Advisory only - no order is placed.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="weeklysignal",
            name="sizing_basis",
            field=models.JSONField(
                blank=True, default=dict, help_text="Snapshot of the sizing inputs, for audit."
            ),
        ),
        migrations.AddField(
            model_name="weeklysignal",
            name="suggested_fraction",
            field=models.FloatField(
                blank=True,
                help_text="Suggested fraction of sizing_capital for this call.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weeklysignal",
            name="suggested_notional",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklysignal",
            name="suggested_shares",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
