# Generated by Django 6.0.8 on 2026-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalfeed", "0002_watchitem_kelly_fraction_watchitem_max_position_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklysignal",
            name="explanation",
            field=models.JSONField(
                blank=True,
                help_text="Best-effort feature attribution for this call, copied from the underlying modeling.ModelPrediction (modeling.explain); null when unavailable for the estimator.",
                null=True,
            ),
        ),
    ]
