# Generated by Django 6.0.8 on 2026-09-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "estimator_key",
                    models.CharField(
                        help_text="Registered estimator key, e.g. 'ridge'. See /modeling/estimators/.",
                        max_length=64,
                    ),
                ),
                (
                    "estimator_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keyword args for the estimator, e.g. {'alpha': 0.5}.",
                    ),
                ),
                (
                    "feature_spec",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of input-feature source descriptors. See modeling.features.",
                    ),
                ),
                (
                    "target_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Output/target descriptor, e.g. {'type': 'horizon_close', 'horizon': 1}.",
                    ),
                ),
                ("train_start", models.DateField(blank=True, null=True)),
                ("train_end", models.DateField(blank=True, null=True)),
                (
                    "holdout_fraction",
                    models.FloatField(
                        default=0.2,
                        help_text="Trailing fraction of rows held out for evaluation (0.05-0.5).",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instruments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Symbols whose history is pooled for training / available for prediction.",
                        related_name="trading_models",
                        to="marketdata.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows", models.PositiveIntegerField(blank=True, null=True)),
                ("feature_count", models.PositiveIntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="modeling.tradingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "as_of",
                    models.DateTimeField(
                        help_text="Decision timestamp the features were built at."
                    ),
                ),
                ("target_date", models.DateField()),
                ("predicted_value", models.FloatField(blank=True, null=True)),
                (
                    "predicted_json",
                    models.JSONField(
                        blank=True,
                        help_text="Vector prediction (multistep) or class probabilities.",
                        null=True,
                    ),
                ),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("abs_error", models.FloatField(blank=True, null=True)),
                ("feature_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_predictions",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="modeling.tradingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "instrument", "target_date"),
                        name="unique_prediction_per_model_instrument_date",
                    )
                ],
            },
        ),
    ]
