# Generated by Django 6.0.8 on 2026-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelprediction",
            name="explanation",
            field=models.JSONField(
                blank=True,
                help_text="Best-effort feature attribution for this prediction (modeling.explain); null when the estimator exposes no usable attribution.",
                null=True,
            ),
        ),
    ]
