# Generated by Django 6.0.8 on 2026-09-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketdata", "0001_initial"),
        ("modeling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("expanding", "Expanding window"), ("rolling", "Rolling window")],
                        default="expanding",
                        max_length=12,
                    ),
                ),
                (
                    "train_span",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="Sessions of training history per fold (rolling: window size).",
                    ),
                ),
                (
                    "test_span",
                    models.PositiveIntegerField(
                        default=21, help_text="Sessions scored per fold before the next retrain."
                    ),
                ),
                (
                    "step",
                    models.PositiveIntegerField(
                        default=21, help_text="Sessions the window advances between folds."
                    ),
                ),
                (
                    "gap",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Embargo sessions left between a fold's train end and its test start.",
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "long_threshold",
                    models.FloatField(
                        default=0.0,
                        help_text="Go long only above this. horizon_close: min fractional gap over the decision close; horizon_return: min predicted return; direction: min P(up) above 0.5.",
                    ),
                ),
                (
                    "allow_short",
                    models.BooleanField(
                        default=False,
                        help_text="Take symmetric short positions on a bearish forecast.",
                    ),
                ),
                ("initial_cash", models.FloatField(default=100000.0)),
                ("commission_bps", models.FloatField(default=0.0)),
                ("slippage_bps", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to="modeling.tradingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("n_folds", models.PositiveIntegerField(blank=True, null=True)),
                ("n_predictions", models.PositiveIntegerField(blank=True, null=True)),
                ("n_trades", models.PositiveIntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "equity_curve",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[iso_date, equity], ...] for the pooled portfolio.",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="backtesting.backtest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("direction", models.SmallIntegerField(default=1, help_text="1 long, -1 short.")),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField()),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField()),
                ("shares", models.FloatField()),
                ("fees", models.FloatField(default=0.0)),
                ("pnl", models.FloatField(default=0.0)),
                ("return_pct", models.FloatField(default=0.0)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_trades",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "entry_date"],
            },
        ),
        migrations.CreateModel(
            name="BacktestPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fold_index", models.PositiveIntegerField()),
                ("as_of", models.DateTimeField()),
                ("target_date", models.DateField()),
                ("predicted_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("abs_error", models.FloatField(blank=True, null=True)),
                (
                    "position",
                    models.SmallIntegerField(default=0, help_text="-1 short, 0 flat, 1 long."),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_predictions",
                        to="marketdata.instrument",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "instrument_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "instrument", "target_date"),
                        name="unique_backtest_prediction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BacktestFold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fold_index", models.PositiveIntegerField()),
                ("train_start", models.DateField()),
                ("train_end", models.DateField()),
                ("test_start", models.DateField()),
                ("test_end", models.DateField()),
                ("n_train", models.PositiveIntegerField(default=0)),
                ("n_test", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folds",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "fold_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "fold_index"), name="unique_fold_per_run"
                    )
                ],
            },
        ),
    ]
