# Generated by Django 6.0.8 on 2026-09-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtesting", "0001_initial"),
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="fit_mode",
            field=models.CharField(
                choices=[
                    ("walk_forward", "Walk-forward (retrain each fold)"),
                    ("frozen_artifact", "Frozen artifact (score a trained model)"),
                ],
                default="walk_forward",
                help_text="walk_forward retrains a fresh pipeline every fold. frozen_artifact loads the model's already-trained joblib artifact and scores every session after it was trained - the fold windows below are ignored.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="training_run",
            field=models.ForeignKey(
                blank=True,
                help_text="frozen_artifact only: which training run's artifact to score. Leave blank to use the model's latest artifact.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backtests",
                to="modeling.modeltrainingrun",
            ),
        ),
    ]
