# Generated by Django 6.0.8 on 2026-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtesting", "0002_backtest_fit_mode_backtest_training_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="looks_leaky",
            field=models.BooleanField(
                default=False,
                help_text="engine.looks_leaky verdict - implausible pooled OOS skill.",
            ),
        ),
    ]
