# Generated by Django 6.0.8 on 2026-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyFundamental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("as_of_report_date", models.DateField()),
                (
                    "ratios",
                    models.JSONField(
                        default=dict, help_text='e.g. {"pe": 8.1, "pb": 1.2, "eps": 4.3, "de": 0.6}'
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["symbol", "-as_of_report_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exchange", "symbol", "as_of_report_date"),
                        name="unique_fundamental_per_symbol_report_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("headline", models.CharField(max_length=512)),
                ("url", models.URLField(max_length=1024)),
                (
                    "url_hash",
                    models.CharField(
                        help_text="sha256 of the canonical URL - the idempotency key for re-ingestion.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=128)),
                ("published_at", models.DateTimeField()),
                (
                    "sentiment",
                    models.FloatField(
                        blank=True,
                        help_text="VADER compound score in [-1, 1]; null if not scored.",
                        null=True,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["exchange", "symbol", "-published_at"],
                        name="research_ne_exchang_2b513d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResearchSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("as_of", models.DateTimeField()),
                ("features", models.JSONField(default=dict)),
                ("sources", models.JSONField(default=list)),
                (
                    "provider_keys",
                    models.JSONField(
                        default=list,
                        help_text="Which feature providers contributed to this snapshot.",
                    ),
                ),
                ("built_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol", "-as_of"],
                "indexes": [
                    models.Index(
                        fields=["exchange", "symbol", "-as_of"],
                        name="research_re_exchang_8ed885_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exchange", "symbol", "as_of"),
                        name="unique_snapshot_per_symbol_as_of",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("platform", models.CharField(max_length=32)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("posted_at", models.DateTimeField()),
                ("sentiment", models.FloatField(blank=True, null=True)),
                (
                    "reach",
                    models.IntegerField(
                        default=0, help_text="followers / upvotes / views - platform-dependent"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["exchange", "symbol", "-posted_at"],
                        name="research_so_exchang_c102db_idx",
                    )
                ],
            },
        ),
    ]
