# Generated by Django 6.0.8 on 2026-08-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["id"]},
        ),
    ]
