# Generated by Django 6.0.8 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("filled", "Filled"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("filled_quantity", models.PositiveIntegerField(default=0)),
                (
                    "filled_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "broker_order_id",
                    models.CharField(
                        blank=True,
                        help_text="ID assigned by the broker adapter. Blank/local-only for PaperBroker.",
                        max_length=64,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("executed_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["executed_at"],
            },
        ),
    ]
