# Generated by Django 6.0.8 on 2026-08-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("marketdata", "0001_initial"),
        ("portfolio", "0001_initial"),
        ("strategies", "0002_strategy_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="portfolio.account",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="marketdata.instrument",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="The Strategy whose signal produced this order, if any (blank for manual/API orders).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="strategies.strategy",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="execution.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["account", "status"], name="execution_o_account_494614_idx"),
        ),
    ]
