# Generated by Django 6.0.8 on 2026-09-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastBacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "predictor_key",
                    models.CharField(
                        help_text="A key registered in forecasting.registry (e.g. 'ridge').",
                        max_length=64,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, help_text="Predictor constructor kwargs."
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="PSX", max_length=16)),
                ("exchange_timezone", models.CharField(default="Asia/Karachi", max_length=64)),
                (
                    "provider_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="research feature providers to assemble; [] means price-only.",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[("expanding", "Expanding window"), ("rolling", "Rolling window")],
                        default="expanding",
                        max_length=12,
                    ),
                ),
                (
                    "train_span",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="Decision rows of training history per fold (rolling: window size).",
                    ),
                ),
                (
                    "test_span",
                    models.PositiveIntegerField(
                        default=21, help_text="Rows scored per fold before the next retrain."
                    ),
                ),
                (
                    "step",
                    models.PositiveIntegerField(
                        default=21, help_text="Rows the window advances between folds."
                    ),
                ),
                (
                    "gap",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Embargo rows between a fold's train end and its test start.",
                    ),
                ),
                ("start", models.DateField(help_text="Earliest feature row assembled.")),
                ("end", models.DateField(help_text="Latest usable label.")),
                ("allow_short", models.BooleanField(default=False)),
                ("long_threshold", models.FloatField(default=0.0)),
                (
                    "cost_bps",
                    models.FloatField(
                        default=0.0, help_text="Round-trip cost charged on position change."
                    ),
                ),
                ("initial_cash", models.FloatField(default=100000.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("n_folds", models.PositiveIntegerField(blank=True, null=True)),
                ("n_skipped_folds", models.PositiveIntegerField(blank=True, null=True)),
                ("n_predictions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Pooled OOS regression scores."
                    ),
                ),
                ("naive_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "trading",
                    models.JSONField(
                        blank=True, default=dict, help_text="Long-if-up translation stats."
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[iso_date, equity], ...] from the trading translation.",
                    ),
                ),
                (
                    "folds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-fold windows + metrics, oldest first.",
                    ),
                ),
                (
                    "predictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Pooled [{fold, as_of, target_date, anchor, ...}].",
                    ),
                ),
                ("skipped_folds", models.JSONField(blank=True, default=list)),
                (
                    "looks_leaky",
                    models.BooleanField(
                        default=False,
                        help_text="engine.looks_leaky verdict - implausible OOS skill.",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
